############################################################################
##                                                                        ##
##                   CosmeticHardcore v2.0 Config                         ##
##                                                                        ##
############################################################################

# The data type you want to store in. Available options: FILE, NBT, DATABASE.
# FILE: will store all data in a playerdata.yml file. (not recommended)
# NBT: will store all data in the players' nbt values.
# DATABASE: will store all data into a MySQL database. Provide database details in sql section. (recommended)
storagetype: "NBT"

# MySQL information. ONLY USED WHEN OPTING FOR DATABASE.
# Only put SSL to true if you know what you're doing.
sql:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "plugin"
  password: "walrus"
  usessl: false

# The displayname of a player with hardcore status. Use %PLAYER% for the playername and '&' for color codes.
hardcorename: "&c%PLAYER%"

# The displayname of a player without hardcore status. Use %PLAYER% for the playername and '&' for color codes.
normalname: "%PLAYER%"

# The default amount of lives a player starts with. Use 1 for real hardcore experience.
defaultlives: 1